# Author: José L. Jorro Aragoneses
# Date: 24/04/2025

#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 7

  data_config:
    strategy: fixed
    dataset_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/
    train_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.train.tsv
    validation_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.valid.tsv
    test_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.test.tsv

  top_k: 100

  models:
    ItemKNN:
      meta:
        save_recs: True
        save_weights: True
        verbose: True
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        validation_metric: nDCG@10
      neighbors: [uniform, 5, 500]
      similarity: [cosine, euclidean, dice, jaccard]
      implementation: classical

  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/itemknn/result
  path_output_rec_weight: outputs/itemknn/weight
  path_output_rec_performance: outputs/itemknn/performance
  path_log_folder: outputs/itemknn/logs

  
