# Author: José L. Jorro Aragoneses
# Date: 22/04/2025

#-----------------------------------------------------
# DATA SETTINGS
#-----------------------------------------------------
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
  inter: ['user_id', 'item_id', 'rating', 'timestamp']

threshoold:
  {'rating': 6.5}

benchmark_filename: ['f0.train', 'f0.valid', 'f0.test']