# Author: José L. Jorro Aragoneses
# Date: 22/04/2025

#-----------------------------------------------------
# DATA SETTINGS
#-----------------------------------------------------
USER_ID_FIELD: user_id
ITEM_ID_FIELD: game_id
RATING_FIELD: rating
TIME_FIELD: timestamp
LABEL_FIELD: rating

load_col:
  inter: ['user_id', 'game_id', 'rating', 'timestamp', 'playing_time_very_short', 'playing_time_short', 'playing_time_moderate', 'playing_time_long', 'playing_time_very_long', 'gaming_mood_party', 'gaming_mood_easy-going', 'gaming_mood_expert', 'gaming_mood_intense', 'gaming_mood_cooperative', 'gaming_mood_competitive', 'gaming_mood_thematic', 'gaming_mood_story-based', 'social_companion_1-player', 'social_companion_2-players', 'social_companion_large-group', 'social_companion_toddlers', 'social_companion_preschoolers', 'social_companion_children', 'social_companion_family', 'social_companion_friends']

threshoold:
  {'rating': 6.5}

benchmark_filename: ['f0.train', 'f0.valid', 'f0.test']