# Author: José L. Jorro Aragoneses
# Date: 22/04/2025

#-----------------------------------------------------
# ENVIRONMENT SETTINGS
#-----------------------------------------------------

gpu_id: 0

# Dataset path and name
data_path: /home/jljorro/Desarrollo/bgg-recsys25/data/
dataset: bgg25_discrete_metadata

model: FM