# Author: José L. Jorro Aragoneses
# Date: 22/04/2025

#-----------------------------------------------------
# EVALUATION SETTINGS
#-----------------------------------------------------

eval_args:
  split: {'RS':[0.8,0.1,0.1]}
  order: TO
  group_by: user
  mode: labeled
  
train_neg_sample_args: ~

metrics: ['auc']
valid_metric: auc
