# Author: José L. Jorro Aragoneses
# Date: 24/04/2025

#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 7

  data_config:
    strategy: fixed
    dataset_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/
    train_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f3.train.tsv
    validation_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f3.valid.tsv
    test_path: /home/jljorro/Desarrollo/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f3.test.tsv

  top_k: 600

  models:
    ItemKNN:
      meta:
        save_recs: True
        save_weights: True
      neighbors: 176
      similarity: euclidean
      implementation: classical

  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/itemknn_f3/result
  path_output_rec_weight: outputs/itemknn_f3/weight
  path_output_rec_performance: outputs/itemknn_f3/performance
  path_log_folder: outputs/itemknn_f3/logs

  
