# Author: José L. Jorro Aragoneses
# Date: 24/04/2025

#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 6.5

  data_config:
    strategy: fixed
    train_path: ../data/bgg25_raw_ratings/bgg25_raw_ratings.f1.train.tsv
    validation_path: ../data/bgg25_raw_ratings/bgg25_raw_ratings.f1.valid.tsv
    test_path: ../data/bgg25_raw_ratings/bgg25_raw_ratings.f1.test.tsv

  top_k: 600

  models:
    MF:
      meta:
        save_recs: True
        save_weights: True
      epochs: 300
      batch_size: 512
      factors: 9
      lr: 1.0704799529633544,
      reg: 1.0069454207436996,
      early_stopping:
        patience: 10
        monitor: nDCG@10
        mode: auto
        verbose: True
        min_delta: 0.001
        rel_delta: 0.1
        baseline: 0.1
        
  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/mf_f1/result
  path_output_rec_weight: outputs/mf_f1/weight
  path_output_rec_performance: outputs/mf_f1/performance
  path_log_folder: outputs/mf_f1/logs

  