# Author: José L. Jorro Aragoneses
# Date: 24/04/2025

#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 6.5

  data_config:
    strategy: fixed
    train_path: ../data/bgg25_raw_ratings/bgg25_raw_ratings.f3.train.tsv
    validation_path: ../data/bgg25_raw_ratings/bgg25_raw_ratings.f3.valid.tsv
    test_path: ../data/bgg25_raw_ratings/bgg25_raw_ratings.f3.test.tsv

  top_k: 600

  models:
    MostPop:
      meta:
        save_recs: True
        save_weights: True

  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/mostpop_f3/result
  path_output_rec_weight: outputs/mostpop_f3/weight
  path_output_rec_performance: outputs/mostpop_f3/performance
  path_log_folder: outputs/mostpop_f3/logs

  