#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 7

  data_config:
    strategy: fixed
    dataset_path: ~/bgg-recsys25/data/bgg25_raw_ratings/
    train_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.train.tsv
    validation_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.valid.tsv
    test_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.test.tsv

  top_k: 600

  models:
    PureSVD:
      meta:
        save_recs: True
        save_weights: True
      seed: 42
      factors: 12
      early_stopping:
        patience: 10
        monitor: nDCG@10
        mode: auto
        verbose: True
        min_delta: 0.001
        rel_delta: 0.1
        baseline: 0.1

  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/puresvd_f0/result
  path_output_rec_weight: outputs/puresvd_f0/weight
  path_output_rec_performance: outputs/puresvd_f0/performance
  path_log_folder: outputs/puresvd_f0/logs
