#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 7

  data_config:
    strategy: fixed
    dataset_path: ~/bgg-recsys25/data/bgg25_raw_ratings/
    train_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f4.train.tsv
    validation_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f4.valid.tsv
    test_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f4.test.tsv

  top_k: 600

  models:
    Random:
      meta:
        save_recs: True
        save_weights: True
      seed: 42

  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/random_f4/result
  path_output_rec_weight: outputs/random_f4/weight
  path_output_rec_performance: outputs/random_f4/performance
  path_log_folder: outputs/random_f4/logs
