#-----------------------------------------------------
# CONFIGURATION CLASSIC ALGORITHMS
#-----------------------------------------------------

experiment:

  gpu: 1

  dataset: bgg25_raw_ratings

  prefiltering:
    strategy: global_threshold
    threshold: 7

  data_config:
    strategy: fixed
    dataset_path: ~/bgg-recsys25/data/bgg25_raw_ratings/
    train_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.train.tsv
    validation_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.valid.tsv
    test_path: ~/bgg-recsys25/data/bgg25_raw_ratings/bgg25_raw_ratings.f0.test.tsv

  top_k: 600

  models:
    UserKNN:
      meta:
        save_recs: True
        save_weights: True
      neighbors: 397
      similarity: euclidean
      implementation: classical

  evaluation:
    cutoffs: [5, 10]
    simple_metrics: [nDCG, MRR, Precision, Recall]

  path_output_rec_result: outputs/userknn_f0/result
  path_output_rec_weight: outputs/userknn_f0/weight
  path_output_rec_performance: outputs/userknn_f0/performance
  path_log_folder: outputs/userknn_f0/logs
