# Author: José L. Jorro Aragoneses
# Date: 22/04/2025

#-----------------------------------------------------
# DATA SETTINGS
#-----------------------------------------------------
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

load_col:
  inter: ['user_id', 'item_id', 'rating']

# unload_col:
#   inter: ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15', 'c16', 'c17', 'c18', 'c19', 'c20']

threshoold:
  {'rating': 6.5}

benchmark_filename: ['f0.train', 'f0.valid', 'f0.test']