# Author: José L. Jorro Aragoneses
# Date: 22/04/2025

#-----------------------------------------------------
# ENVIROMENT SETTINGS
#-----------------------------------------------------

gpu_id: 1

# Dataset path and name
data_path: ../data/
dataset: bgg_24
